Add overwrite option for xtask cross results.
knurling-rs/defmt pull request #512
Opened 2021-06-18 10:47 UTC by derekdreery

#504 rebased and squashed into single commit.

2021-06-20 23:21 UTC, Urhengulas requested changes

2021-06-20 23:21 UTC, Urhengulas commented on xtask/src/main.rs
> +    TestSnapshot {
Let's add a small text, so people know about this option, when running `cargo xtask --help`. I don't have strong feelings about the wording, but this is my suggestion:
```suggestion
    /// Run snapshot tests or optionally update the expected output
    TestSnapshot {
```

2021-06-22 11:33 UTC, Urhengulas commented
bors r+

2021-06-22 11:37 UTC, derekdreery commented
I'll have a look and see if I can implement this now :)

On Tue, 22 Jun 2021, 12:33 Johann Hemmann, ***@***.***> wrote:

> bors r+
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/knurling-rs/defmt/pull/512#issuecomment-865906193>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKT4XQLEFMEVBROU43ZRLDTUBYKJANCNFSM465N2A7Q>
> .
>

2021-06-22 11:39 UTC, merged