decoder: add support for color, style, width and alignment to format
knurling-rs/defmt pull request #769
Opened 2023-08-01 20:40 UTC by andresovela

This PR extends the functionality of the `--log-format` and `--host-log-format` options implemented in #765 by adding support for color, style, width and alignment options.

The format options are pretty much as described in [here](https://github.com/knurling-rs/defmt/pull/765#discussion_r1265257684):

> I can easily imagine assigning static colors, maybe like this "{t:black:bold} [{L:green:dimmed}] Location<{f:yellow:italic}:{l:#5F2A2A:normal}> {s:white:underline}". Note that I A) am using the terms from the colored crate, B) not particularly like that format, it is just what I came up with right now and C) would pick :black:normal as a default.

The `#5F2A2A` variant is not yet supported in this PR, I think the currently implemented options are more than enough.

Something else I still want to implement is support for nested format options or something similar that would allow users to align logs like this:

```
main.rs:15          This is a log
decoder.rs:345      This is another log
```

With the current formatting options this is not possible. I think something like `{{f}:{l}:20:white:underline}` would be a nice syntax to support formatting groups of segments at once.  I'll likely wait for this PR to be merged before working on that though.

One open question is how to implement support for styling `String` log segments, i.e. how do we allow the user to have something like `(HOST) [{L}] {s}` where the `(HOST)` part could be blue, dimmed, etc. It's probably not very important and I can't think of many use cases for this.

2023-08-02 12:24 UTC, Urhengulas requested changes
Thank you for your PR. I like it and will play around a bit more with it and see how it behaves.

One thing I am wondering is, if we can rely a bit more on the functionality from the `colored` crate to make the code a bit more simple on our side. E.g. we could use the `FromStr` implementation from `colored::Color` to simplify the parsing code. Or we could use `colored::Styles` instead of our own `LogStyle`.
I would be against exposing `colored` types in our public API, but as long as they are only internal I think it makes sense to use them and not hand-roll everything by ourselves.

2023-08-02 12:27 UTC, Urhengulas commented on decoder/src/log/format.rs
> +}
Maybe `LogColor`, could be simplified to following? I didn't think it fully through, but I would be happy if it works out.

```suggestion
pub(super) enum LogColor {
    Color(colored::Color),

    /// Color matching the default color for the log level
    SeverityLevel,

    /// Color matching the default color for the log level,
    /// but only if the log level is WARN or ERROR
    WarnError,
}
```

2023-08-03 14:35 UTC, Urhengulas requested changes

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    #[allow(dead_code)]
```suggestion
    #[cfg(test)]
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    #[allow(dead_code)]
```suggestion
    #[cfg(test)]
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    #[allow(dead_code)]
```suggestion
    #[cfg(test)]
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    #[allow(dead_code)]
```suggestion
    #[cfg(test)]
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    });
```suggestion
    let mut parse_type = map_res(take_while(char::is_alphabetic), move |s| {
        let meta = match s {
            "f" => LogMetadata::FileName,
            "F" => LogMetadata::FilePath,
            "l" => LogMetadata::LineNumber,
            "s" => LogMetadata::Log,
            "L" => LogMetadata::LogLevel,
            "m" => LogMetadata::ModulePath,
            "t" => LogMetadata::Timestamp,
            _ => return Err(()),
        };
        Ok(IntermediateOutput::Metadata(meta))
    });
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +    });
```suggestion
    let mut parse_type = map_res(take_while(char::is_alphabetic), move |s| {
        let color = match s {
            "severity" => LogColor::SeverityLevel,
            "werror" => LogColor::WarnError,
            s => match colored::Color::from_str(s) {
                Ok(c) => LogColor::Color(c),
                Err(()) => return Err(()),
            },
        };
        Ok(IntermediateOutput::Color(color))
    });
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
>      });
```suggestion
    let mut parse_type = map_res(take_while(char::is_alphabetic), move |s| {
        let style = match s {
            "bold" => colored::Styles::Bold,
            "italic" => colored::Styles::Italic,
            "underline" => colored::Styles::Underline,
            "strike" => colored::Styles::Strikethrough,
            "dimmed" => colored::Styles::Dimmed,
            _ => return Err(()),
        };
        Ok(IntermediateOutput::Style(style))
    });
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/format.rs
> +            }
```suggestion
            IntermediateOutput::Metadata(m) if metadata.is_none() => metadata = Some(m),
            IntermediateOutput::Color(c) if color.is_none() => color = Some(c),
            IntermediateOutput::Style(s) if style.is_none() => style = Some(s),
            IntermediateOutput::WidthAndAlignment(w) if width_and_alignment.is_none() => {
                width_and_alignment = Some(w)
            }
            _ => return Err(nom::Err::Error(())),
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +        let width = format.width.unwrap_or(self.min_timestamp_width);
Or maybe they could move into `write_string` since it seems it is always called directly afterwards.

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +    }
```suggestion
    match log_color {
        Some(color) => match color {
            LogColor::Color(c) => s.color(c),
            LogColor::SeverityLevel => match level {
                Some(level) => s.color(color_for_log_level(level)),
                None => s,
            },
            LogColor::WarnError => match level {
                Some(level @ (Level::Warn | Level::Error)) => s.color(color_for_log_level(level)),
                _ => s,
            },
        },
        None => s,
    }
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +    }
```suggestion
    match log_style {
        Some(log_style) => match log_style {
            Styles::Bold => s.bold(),
            Styles::Italic => s.italic(),
            Styles::Underline => s.underline(),
            Styles::Strikethrough => s.strikethrough(),
            Styles::Dimmed => s.dimmed(),
            Styles::Clear => s.clear(),
            Styles::Reversed => s.reversed(),
            Styles::Blink => s.blink(),
            Styles::Hidden => s.hidden(),
        },
        None => s,
    }
```

2023-08-03 14:35 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +        }
```suggestion
        Alignment::Left => write!(sink, "{s:<0$}", width),
        Alignment::Center => write!(sink, "{s:^0$}", width),
        Alignment::Right => write!(sink, "{s:>0$}", width),
```

2023-08-03 22:04 UTC, andresovela commented on decoder/src/log/stdout_logger.rs
> +        let width = format.width.unwrap_or(self.min_timestamp_width);
I refactored most of it, feel free to make more suggestions :)

2023-09-20 18:40 UTC, andresovela commented
Hi @Urhengulas, is there any news about this PR?

2023-09-22 08:25 UTC, Urhengulas commented
Hey, I've been sick and busy with other things recently. Will come back to it next week.

2023-09-22 08:49 UTC, andresovela commented
Get well soon :)

2023-09-27 16:48 UTC, Urhengulas requested changes
Looks good! The happy path works nicely.

I just think the error reporting needs to be slightly improved. I found following cases, which both result in the warning and erroneous output below. I assume it is due to a parsing error.

The first case should be rejected, because it is a mistage. I think abort is fine, since the parsing of the log_format will happen at the start of the program.

The second case should be supported in the long run, but it is fine if we error for now. 

- `{t:bold:bold} [{L}] {f}:{l} {s}`
- `{t:bold:underline} [{L}] {f}:{l} {s}`
```
$ DEFMT_LOG=info cargo rb levels
    Finished dev [optimized + debuginfo] target(s) in 0.04s
     Running `/home/urhengulas/Documents/github.com/knurling-rs/krate/./probe-run --chip nRF52840_xxAA --log-format '{t:bold:bold} [{L}] {f}:{l} {s}' target/thumbv7em-none-eabihf/debug/levels`
(HOST) WARN  `defmt::timestamp!` implementation was found, but timestamp is not part of the log format; consider adding the timestamp `{t}` argument to the log format
────────────────────────────────────────────────────────────────────────────────



printlnnn
────────────────────────────────────────────────────────────────────────────────
(HOST) INFO  program has used at least 0.23/254.93 KiB (0.1%) of stack space
(HOST) INFO  device halted without error
```

2023-09-27 16:50 UTC, Urhengulas commented
Also I just realized that `"--host-log-format", "{t} [{L}] {f}:{l} {s}",` results in `<time> [INFO ] mod.rs:131  device halted without error` (note the `<time>`. But this should not be handled in this PR. In theory it should error, but in the long run we might want to add a host timestamp and then it should work.

2023-09-27 21:02 UTC, andresovela commented
Thanks for your feedback :)

I believe I have fixed the issues with the duplicated style specifiers. I also added some tests for that.

2023-09-28 12:25 UTC, Urhengulas approved these changes
🎉

2023-09-28 12:32 UTC, merged