Add support for zero-padded timestamps and Unix-style timestamps
knurling-rs/defmt pull request #780
Opened 2023-10-02 14:49 UTC by andresovela

This PR adds two new format specifiers to allow users to zero-pad their timestamps, or to format the timestamp like this "01:42:56.643".

I also removed the `min_timestamp_width`/`timing_align` stuff that was previously needed for formatting timestamps.

2023-10-02 17:18 UTC, Urhengulas commented
What do you think about doing the zero-padding more similar to the `std::fmt` grammar? https://doc.rust-lang.org/std/fmt/#sign0

```rust
assert_eq!(format!("Hello {:05}!", 5),  "Hello 00005!");
assert_eq!(format!("Hello {:05}!", -5), "Hello -0005!");
assert_eq!(format!("{:#010x}!", 27), "0x0000001b!");
```

For us I would imagine it like this: `"{t:05} [{L}] {s}"`.

2023-10-02 18:45 UTC, andresovela commented
Done

2023-10-03 21:12 UTC, Urhengulas requested changes

2023-10-03 21:12 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +                        let days = timestamp;
```suggestion
                        let div_rem = |x, y| (x / y, x % y);
                        let (timestamp, ms) = div_rem(timestamp, 1000);
                        let (timestamp, seconds) = div_rem(timestamp, 60);
                        let (timestamp, minutes) = div_rem(timestamp, 60);
                        let (timestamp, hours) = div_rem(timestamp, 24);
                        let days = timestamp;
```

2023-10-03 21:12 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +                            let width = format.width.unwrap_or(8);
Why `8` in `unwrap_or(8)`?

2023-10-03 21:12 UTC, Urhengulas commented on decoder/src/log/stdout_logger.rs
> +                        }
Can you please explain this huge if-else?

2023-10-14 17:47 UTC, andresovela commented
I realized that the timestamp customization approach introduced with this PR is not the right approach, so I'll close this PR.

I'll add the padding functionality to #783 instead, and I'll implement the timestamp option as a display hint in a separate PR.

2023-10-14 17:48 UTC, closed without merging

2023-10-15 14:17 UTC, andresovela commented
Opened #789 for the timestamp display hints