Make defmt-print async
knurling-rs/defmt pull request #855
Opened 2024-06-15 14:59 UTC by JomerDev

As discussed in #807 I've split out the work to make defmt-print async into a separate PR.
It changes very little, but please do test it to see if everything still works.
As for the tokio features, I've added all of the features needed instead of using `full` but afaik it wouldn't have made much of a difference as most features were needed anyway.

2024-06-24 08:22 UTC, jonathanpallant commented
Build time (main): `57.09s user 2.33s system 215% cpu 27.534 total`

Build time (PR): `69.60s user 2.75s system 226% cpu 31.895 total`

So an extra 4 seconds to compile, or +15%, on this macBook. I think that's fine.

2024-06-24 08:24 UTC, jonathanpallant approved these changes
Thank you for this PR. The cognitive overhead of switching to Tokio here seems small, so this looks good to me.

2024-06-25 17:36 UTC, Urhengulas requested changes

2024-06-25 17:36 UTC, Urhengulas commented on print/src/main.rs
> +};
```suggestion
use tokio::{
    fs,
    io::{self, AsyncReadExt, Stdin},
    net::TcpStream,
};
```

2024-06-25 17:36 UTC, Urhengulas commented on print/Cargo.toml
> +tokio = { version = "1.38.0", features = ["net", "macros", "time", "rt", "io-util", "fs", "io-std", "sync", "rt-multi-thread"] }
You convinced me

```suggestion
tokio = { version = "1.38", features = ["full"] }
```

2024-06-25 17:36 UTC, Urhengulas approved these changes
Thank you!

2024-06-25 17:43 UTC, merged