Introduce feature to disable blocking mode
knurling-rs/defmt pull request #915
Opened 2024-12-16 15:47 UTC by mdrssv

Hi,

I've added the feature `disable-blocking-mode` which prevents the host from putting rtt into blocking mode, by which I've got bitten a couple of times because I tend to just unplug my devices. However with blocking mode they will just hang once the buffer is full. Since I do not log too much blocking is not of great benefit to me whereas not having the mcu hang is.

2024-12-19 15:45 UTC, Urhengulas requested changes
Looks generally good to me. But I want @jonathanpallant to have a look before merging to ensure it does not interfere with defmt 1.0.

2024-12-19 15:45 UTC, Urhengulas commented on firmware/defmt-rtt/src/channel.rs
> +            _ => Self::nonblocking_write,
```suggestion
            _ if cfg!(feature = "disable-blocking-mode") => Self::nonblocking_write,
            true => Self::blocking_write,
            false => Self::nonblocking_write,
```

2025-01-06 12:41 UTC, jonathanpallant commented
This seems fine to me - it adds a new feature and takes nothing away.

2025-01-07 14:27 UTC, jonathanpallant approved these changes

2025-01-07 14:29 UTC, jonathanpallant commented
@Urhengulas can you clear your blocking marker?

2025-01-08 11:08 UTC, merged